version: '2'

services:
  
  app:
    build: .
    command: echo "Hello, world!"
    volumes:
      - .:/app
    stdin_open: true
    environment:
      BUNDLE_PATH: "/box"
      SKYLIGHT_AUTHENTICATION: "test"
      INSTAGRAM_CLIENT_ID: "test"
      INSTAGRAM_CLIENT_SECRET: "test"

  box:
    image: busybox
    volumes:
      - /box

  web:
    extends:
      service: app
    command: bin/rails s -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    networks:
      - cardistryio
    volumes_from:
      - box

  resque:
    extends:
      service: app
    environment:
      QUEUE: "*"
      RAILS_ENV: development
    command: bin/rake environment resque:work
    networks:
      - cardistryio
    volumes_from:
      - box

  db:
    image: postgres:9.4
    networks:
      - cardistryio

  redis:
    image: redis:alpine
    networks:
      - cardistryio

networks:
  cardistryio:
    # Use a custom driver
    driver: bridge
