version: '2'

services:
  app:
    build: .
    command: echo "Hello, world!"
    volumes:
      - .:/app
    stdin_open: true
    environment:
      BUNDLE_PATH: "/box"

  web:
    extends:
      service: app
    command: bin/rails s -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    networks:
      - cardistryio
    volumes_from:
      - box
    environment:
      DB_HOST: db
      DB_PORT: "5432"

  resque:
    extends:
      service: app
    environment:
      QUEUE: "*"
      RAILS_ENV: development
    command: bin/rake environment resque:work
    networks:
      - cardistryio
    volumes_from:
      - box

  db:
    image: postgres:9.4
    ports:
      - "5432"
    networks:
      - cardistryio

  box:
    image: busybox
    volumes:
      - /box

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - cardistryio

    
networks:
  cardistryio:
    driver: bridge
