default: &default
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: 5
  template: template0
  timeout: 5000
  username: postgres
  host: 'db'
  port: '5432'

development:
  <<: *default
  database: cardistryio_development

test:
  <<: *default
  database: cardistryio_test
