#!/bin/bash
set -e

# Make sure docker is installed
if ! command -v docker-compose > /dev/null; then
cat <<EOF
  You'll need docker and docker-compose

  If you're on OS X or Windows
    - Install the docker toolbox: https://www.docker.com/docker-toolbox
    - Make sure you also install docker-machine
    - When setup is completed make sure to start the app "Docker Quickstart Terminal". It will download and setup the default Docker VM for you

  If you're on Linux, check your package manager for docker and docker-compose
EOF
  exit
fi

# Build docker instance
echo "---- Building docker image"
docker-compose build

# Starts containers and creates network
docker-compose up -d

echo "---- Installing dependencies"
docker-compose run web bundle install

# Add binstubs to PATH via export PATH=".git/safe/../../bin:$PATH" in ~/.zshenv
if [ ! -d .git/safe ]; then
  echo "---- Making .git/safe hack"
  mkdir .git/safe
fi

echo "---- Setting up environment variables"
cp .sample.env .env

docker-compose run -d db
echo "---- Setting up databases"
docker-compose run web bin/rake db:create RAILS_ENV=development
docker-compose run web bin/rake db:create RAILS_ENV=test
docker-compose run web bin/rake db:migrate RAILS_ENV=development
docker-compose run web bin/rake db:migrate RAILS_ENV=test
docker-compose run web bin/rake db:seed RAILS_ENV=development

cat <<EOF

All set!

  Start the app with "docker-compose up"
  When started you can connect at http://localhost:3000

  You should now be able to run the tests with "docker-compose run web bin/rspec"

  If you wanna test adding videos from Instagram you'll need get a client_id and
  client_secret by creating an app on https://instagram.com/developer
  You can add those to .env
  Same goes for testing sending email

EOF
