#!/bin/bash
set -e

# Log files can take up a lot of space, do reset these once in a while
rm -rf log/development.log
rm -rf log/test.log
touch log/development.log
touch log/test.log

if [ $(uname) = "Darwin" ]; then
  echo "---- Making sure docker-machine is running"
  docker-machine start default || true

  echo "---- Connecting to docker-machine"
  eval $(docker-machine env default)
fi

script/migrate
docker-compose build
