#!/bin/bash
set -e

# Log files can take up a lot of space, do reset these once in a while
rm -rf log/development.log
rm -rf log/test.log
touch log/development.log
touch log/test.log

script/migrate
docker-compose build
