#!/bin/bash
set -e

echo "--- Running the tests"
xvfb-run bin/rspec

echo "--- Running bundler-audit"
bin/bundle-audit update
bin/bundle-audit check

echo "--- Running brake man"
bin/brakeman --exit-on-warn
