#!/bin/bash
set -e

rm -rf tmp/pids/server.pid

# Log files can take up a lot of space, do reset these once in a while
rm -rf log/development.log
rm -rf log/test.log
touch log/development.log
touch log/test.log

docker-compose up $@
