#!/bin/bash
set -e

if ! command -v docker > /dev/null; then
  if [ $(uname) = "Darwin" ]; then
    echo "---- Making sure docker-machine is running"
    docker-machine start default || true

    echo "---- Connecting to docker-machine"
    eval $(docker-machine env default)
  fi
fi

if $(docker ps | grep 'web' > /dev/null); then
  echo "--- Running with docker"

  echo "--- Running the tests"
  docker-compose run web bin/rspec $@
else
  echo "Docker isn't running"
  exit 1
fi
