#!/bin/bash
set -e

if !(docker ps | grep spring > /dev/null); then
  echo "Starting spring container"
  docker-compose run -d web script/start-spring
fi

container_name=$(docker ps | grep spring | tr -s " " | awk '{ print $NF }')
echo "Running 'docker exec -it $container_name bin/rspec $@'"
docker exec -it $container_name bin/rspec $@
